# Generated by Django 5.2.6 on 2026-04-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_producto_en_promocion_producto_precio_excesivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to='exum/categorias/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='exum/productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='exum/productos/'),
        ),
    ]
