# Generated by Django 5.2.6 on 2026-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_categoria_imagen_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='exum/banners/')),
                ('boton_texto', models.CharField(blank=True, max_length=100)),
                ('boton_link', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
