# Generated by Django 5.2.6 on 2026-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='imagen',
            new_name='imagen_1',
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='exum/banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='exum/banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='exum/banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='exum/banners/'),
        ),
    ]
