# Generated by Django 5.2.6 on 2026-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_rename_imagen_banner_imagen_1_banner_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
