# Generated by Django 5.2.6 on 2026-04-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_alter_banner_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner',
        ),
    ]
